_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  #WEIGHTS: "output/new2/model_0079999.pth"
  BACKBONE:
    NAME: "build_vgg_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    IN_FEATURES: ["vgg4"]
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
    NUM_CLASSES: 1
    IN_FEATURES: ["vgg4"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 160000
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  BASE_LR: 0.02
DATALOADER:
  SUP_PERCENT: 100.0
  CLASS: ('car',)
DATASETS:
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: (["cityscapes_car",], ["Kitty",])
  TRAIN_UNLABEL: ("Daytime_train",)
  TEST: ("Daytime_val",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 50000
  PROTOTYPE_WARMUP: 49999
  PROTOTYPE_LAYER: 1
  USE_PROTOTYPE: 1
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  USE_CONTRA: 0
  DIS_TYPE: "vgg4"
  CONTRA_WEIGHT: 0.6
  PROTO_WEIGHT: 0.6
TEST:
  EVAL_PERIOD: 5000
